services:
  postgres:
    image: postgres:latest
    container_name: db_postgres_nest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  nest:
    build:
      context: .
      dockerfile: Dockerfile
    image: iagomauricioo/oceanosdeplastico:latest
    container_name: oceanosplastico_api
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pg_data:
