services:
  postgres:
    image: postgres:15
    container_name: db_postgres_nest
    restart: always
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD: 
      POSTGRES_DB:
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_nest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL:
      PGADMIN_DEFAULT_PASSWORD: 
    ports:
      - "5050:80"
    depends_on:
      - postgres
volumes:
  pg_data:
